(require 'core-funs)
(logPrint "加载 core-swiper")
(use-package counsel
      :ensure t)

(use-package swiper
  :defer 3
  :ensure t
  :config
  (progn
    ;; (ivy-mode 1)
    (setq ivy-use-virtual-buffers t)
    (setq enable-recursive-minibuffers t)
    (setq ivy-count-format "(%d/%d) ")
    ;; enable this if you want `swiper' to use it
    ;; (setq search-default-mode #'char-fold-to-regexp)

    
    ;; (global-set-key "\C-s" 'swiper)
    ;; (global-set-key (kbd "C-c C-r") 'ivy-resume)
    ;; (global-set-key (kbd "<f6>") 'ivy-resume)
    ;; (global-set-key (kbd "M-x") 'counsel-M-x)
    ;; (global-set-key (kbd "C-x C-f") 'counsel-find-file)
    ;; (global-set-key (kbd "<f1> f") 'counsel-describe-function)
    ;; (global-set-key (kbd "<f1> v") 'counsel-describe-variable)
    ;; (global-set-key (kbd "<f1> o") 'counsel-describe-symbol)
    ;; (global-set-key (kbd "<f1> l") 'counsel-find-library)
    ;; (global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
    ;; (global-set-key (kbd "<f2> u") 'counsel-unicode-char)
    ;; (global-set-key (kbd "C-c g") 'counsel-git)
    ;; (global-set-key (kbd "C-c j") 'counsel-git-grep)
    ;; (global-set-key (kbd "C-c k") 'counsel-ag)
    ;; (global-set-key (kbd "C-x l") 'counsel-locate)
    ;; (global-set-key (kbd "C-S-o") 'counsel-rhythmbox)
    ;; (define-key minibuffer-local-map (kbd "C-r") 'counsel-minibuffer-history)

    
    ;; (define-key minibuffer-local-map (kbd "C-s") 'swiper-isearch)


    ;; (global-set-key (kbd "C-s") 'swiper-isearch)
    ;; (global-set-key (kbd "M-x") 'counsel-M-x)
    ;; (global-set-key (kbd "C-x C-f") 'counsel-find-file)
    ;; (global-set-key (kbd "M-y") 'counsel-yank-pop)
    ;; (global-set-key (kbd "<f1> f") 'counsel-describe-function)
    ;; (global-set-key (kbd "<f1> v") 'counsel-describe-variable)
    ;; (global-set-key (kbd "<f1> l") 'counsel-find-library)
    ;; (global-set-key (kbd "<f2> i") 'counsel-info-lookup-symbol)
    ;; (global-set-key (kbd "<f2> u") 'counsel-unicode-char)
    ;; (global-set-key (kbd "<f2> j") 'counsel-set-variable)
    ;; (global-set-key (kbd "C-x b") 'ivy-switch-buffer)
    ;; (global-set-key (kbd "C-c v") 'ivy-push-view)
    ;; (global-set-key (kbd "C-c V") 'ivy-pop-view)

    ;; (global-set-key (kbd "C-c c") 'counsel-compile)
    ;; (global-set-key (kbd "C-c g") 'counsel-git)
    ;; (global-set-key (kbd "C-c j") 'counsel-git-grep)
    ;; (global-set-key (kbd "C-c L") 'counsel-git-log)
    ;; (global-set-key (kbd "C-c k") 'counsel-rg)
    ;; (global-set-key (kbd "C-c m") 'counsel-linux-app)
    ;; (global-set-key (kbd "C-c n") 'counsel-fzf)
    ;; (global-set-key (kbd "C-x l") 'counsel-locate)
    ;; (global-set-key (kbd "C-c J") 'counsel-file-jump)
    ;; (global-set-key (kbd "C-S-o") 'counsel-rhythmbox)
    ;; (global-set-key (kbd "C-c w") 'counsel-wmctrl)

    ;; (global-set-key (kbd "C-c C-r") 'ivy-resume)
    ;; (global-set-key (kbd "C-c b") 'counsel-bookmark)
    ;; (global-set-key (kbd "C-c d") 'counsel-descbinds)
    ;; (global-set-key (kbd "C-c t") 'counsel-load-theme)
    ;; (global-set-key (kbd "C-c F") 'counsel-org-file)
    
    )
    :init (advice-add 'swiper :after #'recenter)
    :bind
    ("C-s" . swiper-isearch)
    ("M-x" . counsel-M-x)
    ("C-x C-f" . counsel-find-file)
    ("M-y" . 'counsel-yank-pop)
    ("<f1> f" . counsel-describe-function)
    ("<f1> v" . counsel-describe-variable)
    ("<f1> l" . counsel-find-library)
    ("<f2> i" . counsel-info-lookup-symbol)
    ("<f2> u" . counsel-unicode-char)
    ("<f2> j" . counsel-set-variable)
    ("C-x b" . ivy-switch-buffer)
    ("C-c v" . ivy-push-view)
    ("C-c V" . ivy-pop-view)
    ("C-c c" . counsel-compile)
    ("C-c g" . counsel-git)
    ("C-c j" . counsel-git-grep)
    ("C-c L" . counsel-git-log)
    ("C-c k" . counsel-rg)
    ("C-c m" . counsel-linux-app)
    ("C-c n" . counsel-fzf)
    ("C-x l" . counsel-locate)
    ("C-c J" . counsel-file-jump)
    ("C-S-o" . counsel-rhythmbox)
    ("C-c w" . counsel-wmctrl)
    ("C-c C-r" . ivy-resume)
    ("C-c b" . counsel-bookmark)
    ("C-c d" . counsel-descbinds)
    ("C-c t" . counsel-load-theme)
    ("C-c F" . counsel-org-file)
    )

(provide 'core-swiper)